version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: auth-service:lastest
    container_name: auth-service
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 9001 --reload
    restart: always
    depends_on:
      - dynamodb-local
    env_file:
      - .env
    volumes:
      - .:/code:z
    ports:
      - "9001:9001"
    networks:
      - project-network

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION-us-west-2}
      - DEFAULT_REGION=us-west-2
      - HOSTNAME=${HOSTNAME-localstack}
      - HOSTNAME_EXTERNAL=${HOSTNAME_EXTERNAL-localstack}
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - project-network

networks:
  project-network:
    name: auth-service-network
